### ISSUE TITLE
Choosing the correct pyhon environment

### ISSUE THREAD

**Issue by gauteh** [peterbjorgensen/sved#25]
Hi,

I have python3_host_prog set to a neovim enviroment with the required packages. All works if I don't have another virtual environment activated when starting neovim. However, if I do have another environment activated sved uses that python rather than the one I have configured in neovim. Any way to fix this? Or is this something that needs to be set in sved?

Thanks for this plugin, I have now archived my old one: https://github.com/gauteh/vim-evince-synctex

Regards, Gaute

**Comment by peterbjorgensen** [comment]
Thanks for the reminder. There was already a pull request for this and I have now merged in the changes. Let us know if it doesn't work. https://github.com/peterbjorgensen/sved/commit/2609d23030a5149b47e49cfabe53196d65ba80bf

**Comment by gauteh** [comment]
That did the trick. Thanks!
